[package]
name = "base_test"
version = "0.1.0"
authors = ["MwlLj <731025894@qq.com>"]
edition = "2018"

[dependencies]
exchange_client = { path = "../../" }
rust_parse = { git = "https://github.com/MwlLj/rust_parse" }
