[package]
name = "exchange_service"
version = "0.1.0"
authors = ["MwlLj <731025894@qq.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7", default-features = false, features = ["serde", "v4"] }
rust_parse = { git = "https://github.com/MwlLj/rust_parse" }
